[COREAPI-2116] Adding env structure
madeiramadeirabr/go-service-template pull request #2
Opened 2022-02-02 18:35 UTC by ran-j

[COREAPI-2116]

* feat: added configuration file
* feat: update reade file
* feat: change folder structure

[COREAPI-2116]: https://madeiramadeira.atlassian.net/browse/COREAPI-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-02-02 19:58 UTC, GuilhermeMLS requested changes

2022-02-04 14:55 UTC, PedroFellipe approved these changes
Nice work guys

2022-02-04 15:04 UTC, GuilhermeMLS approved these changes

2022-02-04 15:05 UTC, renatops1991 approved these changes

2022-02-04 15:06 UTC, merged